[variables]
COMPOSER_ALLOW_SUPERUSER = "1"

[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "nodejs_20"]

[phases.install]
cmds = [
    "composer install --ignore-platform-reqs --no-dev --optimize-autoloader",
    "pnpm install"
]

[phases.build]
cmds = [
    "pnpm run build"
]

[start]
cmd = "php artisan config:clear && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
